version: '3.4'

services:
  clouddeployment:
    image: clouddeployment
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 codebases/simple_server/app.py "]
    ports:
      - 5678:5678
